@extends('front.layouts.app')

@section('title', 'Privacy Policy')
@section('header-title', 'Privacy Policy')
@section('header-subtitle', '')


@section('content')
    @include('front.partials.banner')
    <div class="container xl:container-xl mx-auto py-8">

        <p class="text-lg text-gray-700 mb-6">
            Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service
            and explain Your privacy rights and how the law protects You.
        </p>

        <p class="text-lg text-gray-700 mb-6">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection
            and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the
            help of the Privacy Policy Generator.
        </p>

        <h2 class="text-3xl font-semibold mb-4">Interpretation and Definitions</h2>
        <h2 class="text-xl font-semibold mb-4">Interpretation
        </h2>
        <p class="text-lg text-gray-700 mb-6">The words of which the initial letter is capitalized have meanings defined
            under the following conditions. The following definitions shall have the same meaning regardless of whether they
            appear in singular or in plural.</p>
            <h2 class="text-xl font-semibold mb-4">Definitions
            </h2>
        <p class="text-lg text-gray-700 mb-6">
            For the purposes of this Privacy Policy:
        </p>

        <ul class="list-disc list-inside space-y-2 mb-6 text-lg text-gray-700">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our
                Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with
                a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities
                entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers
                to traspasalo.es, Spain.</li>
            <li><strong>Cookies</strong> are small files placed on Your computer, mobile device or any other device by a
                website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: Spain.</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone, or a
                digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li>
        </ul>


        <h2 class="text-3xl font-semibold mb-4">Service refers to the Website.</h2>
        <p class="text-lg text-gray-700 mb-4">
            Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service
            on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how
            the Service is used.
        </p>
        <p class="text-lg text-gray-700 mb-4">
            Third-party Social Media Service refers to any website or any social network website through which a User can
            log in or create an account to use the Service.
        </p>
        <p class="text-lg text-gray-700 mb-4">
            Usage Data refers to data collected automatically, either generated by the use of the Service or from the
            Service infrastructure itself (for example, the duration of a page visit).
        </p>
        <p class="text-lg text-gray-700 mb-4">
            Website refers to traspasalo.es, accessible from https://traspasalo.es/
        </p>
        <p class="text-lg text-gray-700 mb-4">
            You means the individual accessing or using the Service, or the company, or other legal entity on behalf of
            which such individual is accessing or using the Service, as applicable.
        </p>

        <h2 class="text-3xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
        <h2 class="text-2xl font-semibold mb-4">Types of Data Collected</h2>
        <h2 class="text-xl font-semibold mb-4">Personal Data</h2>

        <p class="text-lg text-gray-700 mb-4">While using Our Service, We may ask You to provide Us with certain personally
            identifiable information that can be used to contact or identify You. Personally identifiable information may
            include, but is not limited to:</p>

        <ul class="list-disc list-inside space-y-2 mb-6 text-lg text-gray-700">
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Usage Data</li>
        </ul>


        <h2 class="text-xl font-semibold mb-4"> Usage Data</h2>
        <p class="text-lg text-gray-700 mb-6">
            Usage Data is collected automatically when using the Service.</p>
        <p class="text-lg text-gray-700 mb-6">
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser
            type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent
            on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p class="text-lg text-gray-700 mb-6">
            When You access the Service by or through a mobile device, We may collect certain information automatically,
            including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address
            of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device
            identifiers and other diagnostic data.
        </p>
        <p class="text-lg text-gray-700 mb-6">
            We may also collect information that Your browser sends whenever You visit our Service or when You access the
            Service by or through a mobile device.
        </p>
        <p class="text-lg text-gray-700 mb-6">
            Usage Data is collected automatically when using the Service. It may include information such as Your Device's
            IP address, browser type, browser version, and the pages of our Service that You visit, the time and date of
            Your visit, and the time spent on those pages.
        </p>

        <h2 class="text-3xl font-semibold mb-4">Information from Third-Party Social Media Services</h2>
        <p class="text-lg text-gray-700 mb-6">The Company allows You to create an account and log in to use the Service
            through the following Third-party Social Media Services:</p>

        <ul class="list-disc list-inside space-y-2 mb-6 text-lg text-gray-700">
            <li>Google</li>
            <li>Facebook</li>
            <li>Instagram</li>
            <li>Twitter</li>
            <li>LinkedIn</li>
        </ul>

        <p class="text-lg text-gray-700 mb-6">
            If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may
            collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as
            Your name, Your email address, Your activities or Your contact list associated with that account.
        </p>
        <p class="text-lg text-gray-700 mb-6">
            You may also have the option of sharing additional information with the Company through Your Third-Party Social
            Media Service's account. If You choose to provide such information and Personal Data, during registration or
            otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this
            Privacy Policy.
        </p>

        <h2 class="text-3xl font-semibold mb-4">Tracking Technologies and Cookies</h2>
        <p class="text-lg text-gray-700 mb-6">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
            information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to
            improve and analyze Our Service. The technologies We use may include:</p>

        <p class="text-lg text-gray-700 mb-6"> Cookies or Browser Cookies. A cookie is a small file placed on Your Device.
            You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You
            do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your
            browser setting so that it will refuse Cookies, our Service may use Cookies.
            Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web
            beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for
            example, to count users who have visited those pages or opened an email and for other related website statistics
            (for example, recording the popularity of a certain section and verifying system and server integrity).
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile
            device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can
            learn more about cookies on TermsFeed website article.</p>
    </div>

    @include('front.partials.footer')
@endsection
